# Generated by Django 4.1.7 on 2023-03-11 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
                ('cpf', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
                ('cpf', models.CharField(max_length=20)),
                ('areaFormacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('descricao', models.CharField(max_length=500)),
                ('ano', models.IntegerField()),
                ('cronograma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teste.cronograma')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('descricao', models.CharField(max_length=500)),
                ('areaProjeto', models.CharField(max_length=100)),
                ('autores', models.ManyToManyField(to='teste.autor')),
                ('premio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teste.premio')),
            ],
        ),
        migrations.CreateModel(
            name='EnviarProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('resumo', models.CharField(max_length=500)),
                ('dataEnvio', models.DateField()),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliarProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parecer', models.CharField(max_length=100)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dataAvaliacao', models.DateField()),
                ('avaliador', models.ManyToManyField(to='teste.avaliador')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste.projeto')),
            ],
        ),
    ]
