# Generated by Django 4.1.7 on 2023-03-25 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliarprojeto',
            name='projeto',
        ),
        migrations.AddField(
            model_name='avaliarprojeto',
            name='projetoEnviado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teste.enviarprojeto'),
            preserve_default=False,
        ),
    ]
