# Generated by Django 4.1.7 on 2023-05-31 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0002_remove_avaliarprojeto_projeto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enviarprojeto',
            name='area',
        ),
        migrations.RemoveField(
            model_name='enviarprojeto',
            name='resumo',
        ),
        migrations.RemoveField(
            model_name='enviarprojeto',
            name='titulo',
        ),
    ]
